### ISSUE TITLE
[Dialog] focus issue

### ISSUE THREAD

**Issue by ajdiyassin** [radix-ui/themes#174] opened 2023-12-06 09:59 UTC
I have an issue where when Dialog is visible it focuses on the first element that has the focus property

Some elements that got focus on the first render:

1. Tooltips
2. Tabs

It's annoying to get tooltips triggered just by opening the dialog modal.

**Comment by vladmoroz** [comment] 2023-12-06 10:18
This is by design and based on the [ARIA modal dialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/). However, you can prevent the default focus behaviour and re-route the focus to another element using `onOpenAutoFocus` prop:

```jsx
<Dialog.Content
  onOpenAutoFocus={(event) => {
    event.preventDefault();
    elementToFocusRef.current?.focus();
  }}
/>
```

This way you can re-route the focus to another interactive element; moving it to Dialog.Content itself is also acceptable.

**Closed by vladmoroz** 2023-12-06 10:18 UTC
