### ISSUE TITLE
How about a date picker component?

### ISSUE THREAD

**Issue by caburj** [radix-ui/themes#112] opened 2023-10-08 09:17 UTC
It would be nice to have such component that complements with the theme.

**Comment by IgnusG** [comment] 2023-11-13 19:09
I think these 2 are duplicates https://github.com/radix-ui/themes/issues/69. Perhaps you can join forces?

**Comment by vladmoroz** [comment] 2024-01-04 09:33
Closing as a duplicate of #69

**Closed by vladmoroz** 2024-01-04 09:33 UTC
